// Generated by CoffeeScript 1.3.3
(function() {
  var Orgnr;

  module.exports = function(port) {
    return new Orgnr(port);
  };

  Orgnr = (function() {

    function Orgnr(str) {
      this.str;
    }

    return Orgnr;

  })();

  this;


}).call(this);
